name: Release VSCE & OVSX

on:
  push:
    tags:
      - '@proj-airi/airi-plugin-vscode@v*'
      - 'v*'

permissions:
  contents: read

jobs:
  release-vsix:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/setup@v2
        with:
          runtime: node@26.7.0
          cache: true
          install: false

      - name: Configure npm registry
        uses: actions/setup-node@v6
        with:
          # registry-url required. Learn more at
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:packages
      - run: pnpm run -F @proj-airi/airi-plugin-vscode build
      - run: pnpm run -F vscode-airi build
      - run: pnpm run publish
        working-directory: ./integrations/vscode/vscode-airi
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
